### PR TITLE
Adding Magento version detection

### PR DESCRIPTION
**Pull request by Nic062**
Hello, 

Magento detection version via magento_version file.

Regards

### CODE REVIEW

**Comment by Nic062** [comment]
Just, i forget to set "vd" to 1  in cmseekdb/cmss.py : 

> mg = {
    'name':'Magento',
    'url':'https://magento.com',
    'vd':'1',
    'deeps':'0'
}

**Comment by Tuhinshubhra** [comment]
Cool, once i verify I'll merge it shortly

**Comment by Tuhinshubhra** [comment]
@Nic062 can you provide me with some target that has the 'magento_version' file?

**Comment by Tuhinshubhra** [comment]
added.. thanks for helping me improve cmseek ;)

**Comment by Nic062** [comment]
Some example  :
https://www.paulsmith.com/uk
https://www.tomdixon.net/
https://www.hellyhansen.com/
https://www.choconchoc.co.uk/

With pleasure ;)

**Pull request closed without merging**
